### ISSUE TITLE
Warning when compiling with geom.h

### ISSUE THREAD

**Issue by peterrdf** [I-Sokolov/RDFGeomApi#2]
The following code generates a warning:

    template <typename TList, typename TElem> void ListToArray(const TList& values, TElem** arr, int64_t* count)
    {
        *count = 0;
        for (const TElem v : values) {
            (*count)++;
        }

The warning is that v is initialized but not used.

**Comment by peterrdf** [comment]
@I-Sokolov I-Sokolov

**Comment by I-Sokolov** [comment]
@peterrdf what compiler are you using,
I can not reproduce with VS2019

**Comment by peterrdf** [comment]
Hi I-Sokolov, I am using VS 2022, the warning is however clean and valid in my perception, v is initialized and not used
